### ISSUE TITLE
Yoon on stage

### ISSUE THREAD

**Issue by ksks2211** [ksks2211/Quarte1-github_prac#1]
자세한 내용을 입력하면 됩니다.
3e7cc635785418b7a5f7f254e712d8c213cdb634

**Comment by ksks2211** [comment]
stage end

**Comment by kkll22** [comment]
몰라 알수가 없어

**Comment by ksks2211** [comment]
Close issue

**Comment by kkll22** [comment]
reopen issue for no reason

**Comment by ksks2211** [comment]
and close it once again for no reason.
